name: 'Lint and Format'
description: 'Run linting and formatting checks'
inputs:
  cache-key:
    description: 'Cache key suffix'
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js with cache
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Restore cached node_modules
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-${{ inputs.cache-key }}
        restore-keys: |
          deps-${{ runner.os }}-

    - name: Run linting
      run: npm run lint:ci
      shell: bash

    - name: Check formatting
      run: npm run format:ci
      shell: bash
