name: Run and test the docker image
description: Run and test the docker image.

inputs:
  image_name:
    description: The name of the docker image
    required: true
  app_name:
    description: The name of the application
    required: true

runs:
  using: composite
  env:
    PORT: ${PORT:-3000}
    IMAGE_NAME: ${{ inputs.image_name }}
    CONTAINER_NAME: ${{ inputs.app_name }}-ci
  steps:
    - name: Create secret files directory
      shell: bash
      run: |
        mkdir -p .ci-secrets
        chmod 700 .ci-secrets
        
    - name: Write secrets to files
      shell: bash
      env:
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
      run: |
        echo "${DATABASE_PASSWORD}" > .ci-secrets/database_password
        echo "${REDIS_PASSWORD}" > .ci-secrets/redis_password
        echo "${JWT_SECRET}" > .ci-secrets/jwt_secret
        
        chmod 600 .ci-secrets/*
        
        echo "✓ Secret files created"

    - name: Build the image
      run: |
        docker compose -f docker-compose.ci.yml build

    - name: Start the container
      run: |
        docker compose -f docker-compose.ci.yml up -d

    - name: Trivy vulnerability scan
      uses: aquasecurity/trivy-action@0.19.0
      with:
        image-ref: ${{ env.IMAGE_NAME }}
        format: table
        exit-code: 1
        severity: CRITICAL,HIGH
        ignore-unfixed: true
        skip-dirs: /usr/local/lib/node_modules/npm

    - name: Docker Scout
      uses: docker/scout-action@v1.3.1
      with:
        command: cves
        image: ${{ env.IMAGE_NAME }}
        exit-code: true
        only-severities: critical,high
        ignore-base: true

    - name: Snyk container scan
      uses: snyk/actions/docker@0.5.0
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{ env.IMAGE_NAME }}
        args: |
          --severity-threshold=high
          --exclude=/usr/local/lib/node_modules/npm

    - name: Test the container
      run: |
        set -euo pipefail

        HEALTH_CHECK_TIMER=60
        HEALTH_OK=false

        for ((i=1; i<=${HEALTH_CHECK_TIMER}; i++)); do
          echo -ne "⏳ Checking... ${i}/${HEALTH_CHECK_TIMER}s\r"

          if ! docker ps --filter "name=${CONTAINER_NAME}" --format "{{.Names}}" | grep -q "^${CONTAINER_NAME}$"; then
            echo "❌ Container stopped unexpectedly"
            docker logs "${CONTAINER_NAME}" || true
            HEALTH_OK=false
            break
          fi

          if docker exec "${CONTAINER_NAME}" sh -c "curl -f -s --max-time 3 http://localhost:${PORT}/api/v1/health >/dev/null"; then
            echo "✅ Health OK after ${i}s"
            HEALTH_OK=true
            break
          fi

          sleep 1
        done

        echo ""

        if [ "${HEALTH_OK}" = "true" ]; then
          echo "✅ Test passed"
        else
          echo "❌ Health check failed"
          echo "Container logs:"
          docker logs "${CONTAINER_NAME}" || true
          exit 1
        fi

    - name: Cleanup
      if: always()
      run: |
        set +e

        echo "Cleaning up the container: ${CONTAINER_NAME}"
        docker compose -f docker-compose.ci.yml down 2>/dev/null || true
        echo "✅ The docker container stopped and removed."

        sleep 2

        echo "Cleaning up secrets..."
        rm -rf .ci-secrets 2>/dev/null || true
        echo "✅ The secret file removed."
        
        echo "✅ Cleanup complete."
