name: Setup Node.js and dependencies with cache
description: >
  Sets up Node.js, restores node_modules from cache if available, and installs
  dependencies if missing. Works across jobs and workflows.

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Setup Node.js with cache
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-lock.yaml'

    - name: Install dependencies
      shell: bash
      run: pnpm run install:ci
