name: Setup Node.js and dependencies with cache
description: >
  Sets up Node.js, restores node_modules from cache if available, and installs
  dependencies if missing. Works across jobs and workflows.

runs:
  using: composite
  steps:
    - name: Setup Node.js with cache
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Install dependencies
      shell: bash
      run: npm ci
