name: 'Setup Node.js with Caching'
description: 'Setup Node.js and restore node_modules cache if available'
inputs:
  cache-hit:
    description: 'Whether cache was hit in install-dependencies job'
    required: true
    default: 'false'
  node-version:
    description: 'Node.js version'
    required: false
    default: '20'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Restore cached dependencies
      if: inputs.cache-hit == 'true'
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies if cache missed
      if: inputs.cache-hit != 'true'
      shell: bash
      run: npm ci
