name: Run docker image
description: Run docker image

inputs:
  image_name:
    description: The image name
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Run the image
      shell: bash
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/${{ vars.APP_NAME }}-${{ inputs.image_name }}"
        docker pull "${IMAGE_NAME}"
        docker run --rm \
          -v ${{ github.workspace }}:/github/workspace \
          "${IMAGE_NAME}"
