name: ci-expense-api

services:
    expense-api:
        image: ${IMAGE:?ERROR IMAGE must be provided}
        build:
            context: .
            target: production
            dockerfile: Dockerfile

    postgres:
        environment:
            - WALG_S3_PREFIX=s3://expense-api/db-backup/ci

    postgres-backup:
        environment:
            - WALG_S3_PREFIX=s3://expense-api/db-backup/ci
