services:
    expense-api:
        image: ${IMAGE_NAME:?ERROR IMAGE_NAME is required}
        stdin_open: true
        tty: true
        env_file:
            - .env
        environment:
            - DATABASE_PASSWORD_FILE=/run/secrets/database_password
            - REDIS_PASSWORD_FILE=/run/secrets/redis_password
            - JWT_SECRET_FILE=/run/secrets/jwt_secret
            - MAIL_USERNAME_FILE=/run/secrets/mail_username
            - MAIL_PASSWORD_FILE=/run/secrets/mail_password
            - GOOGLE_OAUTH_CLIENT_ID_FILE=/run/secrets/google_oauth_client_id
            - GOOGLE_OAUTH_CLIENT_SECRET_FILE=/run/secrets/google_oauth_client_secret
        build:
            context: .
            target: development
            dockerfile: Dockerfile
        ports:
            - '4000:4000'
            - '9229:9229'
        networks:
            - expense-api-network
        healthcheck:
            test:
                - 'CMD-SHELL'
                - 'curl -s http://localhost:4000/v1/api/health | grep -q "\"status\":\"ok\"" || exit 1'
            interval: 15s
            timeout: 5s
            start_period: 30s
            retries: 3
        secrets:
            - database_password
            - redis_password
            - jwt_secret
            - mail_username
            - mail_password
            - google_oauth_client_id
            - google_oauth_client_secret
        volumes:
            - ./src:/usr/src/app/src
            - ./package.json:/usr/src/app/package.json
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
        restart: unless-stopped
        pull_policy: never

    postgres:
        image: postgres:16-alpine
        environment:
            - POSTGRES_DB=expense_api_dev
            - POSTGRES_USER=expense_api
            - POSTGRES_PASSWORD_FILE=/run/secrets/database_password
            - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
            - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
        secrets:
            - database_password
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        networks:
            - expense-api-network
        healthcheck:
            test:
                - 'CMD-SHELL'
                - 'pg_isready -U expense_api'
            interval: 15s
            timeout: 5s
            start_period: 30s
            retries: 3
        restart: unless-stopped

    redis:
        image: redis:7-alpine
        command: >
            sh -c "
            redis-server 
                --requirepass \"$$(cat /run/secrets/redis_password)\"
                --appendonly yes
            "
        secrets:
            - redis_password
        volumes:
            - redis-data:/data
        ports:
            - '6379:6379'
        networks:
            - expense-api-network
        healthcheck:
            test:
                - 'CMD'
                - 'redis-cli'
                - 'ping'
            interval: 15s
            timeout: 5s
            start_period: 30s
            retries: 3
        restart: unless-stopped

    kafka:
        image: apache/kafka:4.0.0
        restart: unless-stopped
        ports:
            - '9092:9092'
        environment:
            - KAFKA_NODE_ID=1
            - KAFKA_PROCESS_ROLES=broker,controller
            - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
            - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
            - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
            - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
            - KAFKA_LOG_DIRS=/var/lib/kafka/data
            - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
            - KAFKA_DELETE_TOPIC_ENABLE=true
            - KAFKA_LOG_RETENTION_HOURS=720
        volumes:
            - kafka_data:/var/lib/kafka/data
        healthcheck:
            test:
                - 'CMD-SHELL'
                - '/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1'
            interval: 15s
            timeout: 5s
            retries: 5
            start_period: 60s
        networks:
            - expense-api-network

    debezium-connect:
        image: mohammadnowresideh1997/debezium-connect:3.0.8.Final
        restart: unless-stopped
        depends_on:
            postgres:
                condition: service_healthy
            kafka:
                condition: service_healthy
        ports:
            - '8083:8083'
        environment:
            - BOOTSTRAP_SERVERS=kafka:9092
            - GROUP_ID='1'
            - CONFIG_STORAGE_TOPIC=connect_configs
            - OFFSET_STORAGE_TOPIC=connect_offsets
            - STATUS_STORAGE_TOPIC=connect_statuses
            - KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
            - VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
            - KEY_CONVERTER_SCHEMAS_ENABLE=false
            - VALUE_CONVERTER_SCHEMAS_ENABLE=false
            - CONNECT_REST_ADVERTISED_HOST_NAME=debezium-connect
            - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
            - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
            - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
            - CONNECT_REST_PORT=8083
            - CONNECT_LOG4J_ROOT_LOGLEVEL=DEBUG
        healthcheck:
            test:
                - 'CMD-SHELL'
                - 'curl -fs http://localhost:8083/ | grep version >/dev/null'
            interval: 15s
            timeout: 5s
            retries: 5
            start_period: 45s
        networks:
            - expense-api-network

    debezium-init:
        build:
            context: .
            dockerfile: Dockerfile.debeziumInit
        restart: no
        depends_on:
            debezium-connect:
                condition: service_healthy
        environment:
            - DATABASE_HOST=postgres
            - DATABASE_PORT=5432
            - DATABASE_NAME=expense_api_dev
            - DATABASE_USER=expense_api
            - DATABASE_PASSWORD_FILE=/run/secrets/database_password
        secrets:
            - database_password
        networks:
            - expense-api-network

volumes:
    postgres-data:
        driver: local
    redis-data:
        driver: local
    kafka_data:
        driver: local

secrets:
    database_password:
        file: ./secrets/database_password.txt
    redis_password:
        file: ./secrets/redis_password.txt
    jwt_secret:
        file: ./secrets/jwt_secret.txt
    mail_username:
        file: ./secrets/mail_username.txt
    mail_password:
        file: ./secrets/mail_password.txt
    google_oauth_client_id:
        file: ./secrets/google_oauth_client_id.txt
    google_oauth_client_secret:
        file: ./secrets/google_oauth_client_secret.txt

networks:
    expense-api-network:
        driver: bridge
