FROM alpine:3.22

RUN apk add --no-cache tar

COPY ./scripts/database/replaceEntrypoint.sh /usr/local/bin/replaceEntrypoint.sh

RUN chmod +x /usr/local/bin/replaceEntrypoint.sh

ENTRYPOINT ["/usr/local/bin/replaceEntrypoint.sh"]
