FROM postgres:16

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl ca-certificates && \
    rm -rf /var/lib/apt/lists/* && \
    curl -L https://github.com/wal-g/wal-g/releases/download/v3.0.5/wal-g-pg-ubuntu-22.04-amd64.tar.gz | tar -xz && \
    mv wal-g-pg-ubuntu-22.04-amd64 /usr/local/bin/wal-g && \
    chmod 755 /usr/local/bin/wal-g && \
    curl -fsSL https://github.com/aptible/supercronic/releases/latest/download/supercronic-linux-amd64 -o /usr/local/bin/supercronic && \
    chmod +x /usr/local/bin/supercronic

COPY dbBackup.cron /etc/dbBackup.cron
COPY ./scripts/database/backup.sh /usr/local/bin/backup.sh
COPY ./scripts/database/entrypoint.sh /usr/local/bin/entrypoint.sh

RUN chmod +x \
    /usr/local/bin/backup.sh \
    /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["postgres"]
