name: Detect Branch name
description: Detects current branch name

runs:
  using: docker
  image: Dockerfile
  args:
    - --file=./scripts/ci/detectBranchName/Dockerfile

branding:
  icon: git-branch
  color: blue
