name: Run docker image
description: Run docker image

inputs:
  image_name:
    description: The image name
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Run the image
      shell: bash
      run: |
        docker run --rm ${{ inputs.image_name }}
