name: Load Docker Image
description: Loads a Docker image from saved artifact

inputs:
  image_latest:
    description: Latest image tag
    required: true
  image_sha:
    description: SHA image tag
    required: true
  artifact_path:
    description: Path to saved images
    required: true

runs:
  using: composite
  steps:
    - name: Load Docker image
      shell: bash
      run: |
        LATEST_FILENAME=$(echo "${{ inputs.image_latest }}" | sed 's|/|_|g' | sed 's|:|-|g').tar
        SHA_FILENAME=$(echo "${{ inputs.image_sha }}" | sed 's|/|_|g' | sed 's|:|-|g').tar

        echo "Looking for saved files:"
        echo "1. ${LATEST_FILENAME}"
        echo "2. ${SHA_FILENAME}"

        if [ -f "${{ inputs.artifact_path }}/${LATEST_FILENAME}" ]; then
          echo "Loading from: ${LATEST_FILENAME}"
          docker load -i "${{ inputs.artifact_path }}/${LATEST_FILENAME}"
        elif [ -f "${{ inputs.artifact_path }}/${SHA_FILENAME}" ]; then
          echo "Loading from: ${SHA_FILENAME}"
          docker load -i "${{ inputs.artifact_path }}/${SHA_FILENAME}"
        else
          echo "❌ No saved image found!"
          echo "Available files in ${{ inputs.artifact_path }}/:"
          ls -la "${{ inputs.artifact_path }}/" || true
          exit 1
        fi

        echo "Available tags after loading:"
        if docker image inspect "${{ inputs.image_latest }}" > /dev/null 2>&1; then
          echo "✅ ${{ inputs.image_latest }} exists"
        else
          echo "❌  ${{ inputs.image_latest }} not found"
          exit 1
        fi

        if docker image inspect "${{ inputs.image_sha }}" > /dev/null 2>&1; then
          echo "✅ ${{ inputs.image_sha }} exists"
        else
          echo "❌  ${{ inputs.image_sha }} not found"
          exit 1
        fi

        echo "✅ Images loaded successfully"
