#!/usr/bin/env sh

set -euo pipefail

source ./.husky/husky.sh
source ./scripts/common/logs.sh

log_info "🚀 Running commit-msg checks..."

pnpm run validate:commit:message $1

log_success "✅ All commit-msg checks passed!"
