name: Master CI

on:
    workflow_run:
        workflows: ['PR CI']
        types:
            - completed
        branches:
            - master

concurrency:
    group: ${{ github.workflow }}-${{ github.event.workflow_run.head_sha || github.sha }}
    cancel-in-progress: true

env:
    SHA: ${{ github.event.workflow_run.head_sha || github.sha }}

jobs:
    run-and-test:
        if: github.event.workflow_run.conclusion == 'success'
        timeout-minutes: 30
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the source
              uses: actions/checkout@v4
              with:
                  ref: ${{ env.SHA }}

            - name: Install node and node_modules
              uses: ./.github/actions/setup-node

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Create secrets for Docker Compose
              run: |
                  mkdir -p secrets
                  echo "${{ secrets.DATABASE_PASSWORD }}" > ./secrets/database_password.txt
                  echo "${{ secrets.REDIS_PASSWORD }}" > ./secrets/redis_password.txt
                  echo "${{ secrets.JWT_SECRET }}" > ./secrets/jwt_secret.txt
                  echo "${{ secrets.MAIL_USERNAME }}" > ./secrets/mail_username.txt
                  echo "${{ secrets.MAIL_PASSWORD }}" > ./secrets/mail_password.txt
                  echo "${{ secrets.MAIL_TO }}" > ./secrets/mail_to.txt
                  echo "${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}" > ./secrets/google_oauth_client_id.txt
                  echo "${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}" > ./secrets/google_oauth_client_secret.txt
                  echo "${{ secrets.ELASTICSEARCH_PASSWORD }}" > ./secrets/elasticsearch_password.txt

                  chmod 600 ./secrets/elasticsearch_password.txt

            - name: Run the entrypoint
              id: run-entrypoint
              run: pnpm run start:docker:ci
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  TAG: ${{ env.SHA }}

            - name: Scan the docker image
              uses: ./.github/actions/scan-docker-image
              with:
                  image_name: ${{ steps.run-entrypoint.outputs.image_name }}
                  snyk_token: ${{ secrets.SNYK_TOKEN }}

            - name: Cleanup secrets
              if: always()
              run: rm -rf ./secrets

            - name: Log out from DockerHub
              if: always()
              run: docker logout
