name: Master CI

on:
    workflow_run:
        workflows: ['PR CI']
        types:
            - completed
        branches:
            - master

concurrency:
    group: ${{ github.workflow }}-${{ github.event.workflow_run.head_sha || github.sha }}
    cancel-in-progress: true

env:
    SHA: ${{ github.event.workflow_run.head_sha || github.sha }}

jobs:
    run-and-test:
        if: github.event.workflow_run.conclusion == 'success'
        timeout-minutes: 30
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the source
              uses: actions/checkout@v4
              with:
                  ref: ${{ env.SHA }}

            - name: Install node and node_modules
              uses: ./.github/actions/setup-node

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Create secrets for Docker Compose
              run: |
                  mkdir -p secrets
                  echo "${{ secrets.DATABASE_PASSWORD }}" > ./secrets/database_password.txt
                  echo "${{ secrets.REDIS_PASSWORD }}" > ./secrets/redis_password.txt
                  echo "${{ secrets.JWT_SECRET }}" > ./secrets/jwt_secret.txt

            - name: Run the enptrypoint
              run: pnpm run start:docker:ci
              env:
                  MODE: ci
                  COMPOSE_FILE: docker-compose.ci.yml
                  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ vars.APP_NAME }}-ci:${{ env.SHA }}

            - name: Scan the docker image
              uses: ./.github/actions/scan-docker-image
              with:
                  image_name: ${{ secrets.DOCKER_USERNAME }}/${{ vars.APP_NAME }}-ci:${{ env.SHA }}

            - name: Clean up secrets
              if: always()
              run: rm -rf ./secrets
